### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by BianChengNan** [revir/FairyDict#1]
使用了一下，感觉挺赞的。特地来提建议，希望可以考虑。
- 能否增加按住ctrl或者alt键再开启翻译功能的选项？现在很多情况下会意外弹出翻译框！实在是烦。
- 弹出的页面太大了，很容易遮挡要看的内容，能否缩小一些？并且显示位置再智能一些，比如在所选位置的上方。显示效果可以参考[词焙+](https://github.com/vilic/wordsbaking-plus-chrome)，非常精简实用。
- 能否提供apikey的自定义功能？这样就不用担心用的人多，导致不能翻译的问题了。
- 其它配置可以参考 [划词翻译](https://github.com/Selection-Translator/crx-selection-translate)

总体来说响应还是很给力的，点赞！

**Comment by revir** [comment]
@BianChengNan 
已更新，增加了一大批在线词典 :)
1. 你提的第一点需求已经实现了，进入选项页可以设置需要按住的键。
2. 弹出的窗口是可以拖动放大缩小的，每次查询之后你的设置会保存。
3. 现在除了金山词霸和Bible，没有通过 api 调用的词典， 爱词霸好像没听说有接口限制？
