### ISSUE TITLE
能否自定义弹出气泡的位置

### ISSUE THREAD

**Issue by xshrim** [revir/FairyDict#14]
感谢作者开发了这么好用的查词插件。有一个小需求不知道作者能不能提供一下，就是划词后出现的黑色气泡小窗口默认是显示在鼠标右下角。但是这个会被别的插件的界面给覆盖了（比如selection search这种选中关键字弹出气泡工具条的插件），所以能不能提供一个自定义弹出位置的功能，能够在鼠标上方显示划词气泡？

**Comment by revir** [comment]
你期待已久的功能在 3.1 版本里来了  :)
不但可以设置显示位置，还可以设置是否跟着鼠标移动。
