### ISSUE TITLE
翻译看不清

### ISSUE THREAD

**Issue by SharerMax** [revir/FairyDict#15]
![image](https://user-images.githubusercontent.com/9065684/28818508-e4d01cb4-76dd-11e7-85ae-5ec87598bf40.png)

复现地址： https://msdn.microsoft.com/en-us/library/bb308959.aspx

**Comment by revir** [comment]
同样也在这里有问题： https://docs.docker.com/get-started/

**Comment by revir** [comment]
Fixed on v3.1
