### ISSUE TITLE
ubuntu上不能用

### ISSUE THREAD

**Issue by jinhe1314** [revir/FairyDict#2]
ubuntu上不能用

**Comment by revir** [comment]
不是吧？ 这是一个 Chrome 扩展啊，只要是chrome浏览器都能用，与操作系统无关的。能否给个详细一点的描述？ 你用的什么浏览器？ 版本是多少？ 你是从本地 crx 文件安装还是 Chrome webstore 上安装的？

我在 Arch linux 和 Mac 上都可以正常使用。

**Comment by jinhe1314** [comment]
ubuntu 16.04 
Chrome webstore 上安装的
表现是不能取词，快捷键也不能唤出词典界面。

**Comment by revir** [comment]
谢谢反馈！
1. 安装后是需要刷新页面才能使用的，刷新了吗？
2. 页面 URL 是？ 我来测试一下
3. 有三种方式打开词典，鼠标取词，快捷键，右键菜单。你能从右键菜单打开吗？
4. 能否打开 Console 看看有没有报错？

**Comment by jinhe1314** [comment]
鼠标取词，快捷键取词不可以，右键可以。
Console 没有报错

**Comment by revir** [comment]
这种情况应该是没刷新页面。也有极少数网站页面不支持，比如你在 chrome webstore 里是不能取词的。
你的url是？

**Comment by jinhe1314** [comment]
要选中双击才可以

**Comment by revir** [comment]
不应该呀，其他网站呢？
能否给我url我测试一下能否复现~

**Comment by jinhe1314** [comment]
随便什么网址

**Comment by revir** [comment]
我想我懂你的意思了。

这个取词不同于一般的桌面 APP， 需要你自己选中单词，或双击选择一个单词，或拖动选择一段，等你鼠标松开后(mouseup event)才会查询。

有些桌面程序确实只要按了快捷键，就会在当前鼠标指针的下面自动通过读屏获得指针附近的单词，但是网页程序上办不到。

**Comment by jinhe1314** [comment]
明白了
最好在帮助中写一下
