### ISSUE TITLE
Ctrl 快速查词失效

### ISSUE THREAD

**Issue by Hylenbin** [revir/FairyDict#23]
Chrome 版本：  63.0.3239.132（正式版本） （64 位）
问题详述：按住Ctrl键，鼠标悬停在某个英文单词上面，单词被选定，弹出透明色打黑色查词框瞬间消失如下图所示

![image](https://user-images.githubusercontent.com/32305724/34647227-c1c1b2a8-f3b7-11e7-9682-3dc59100b180.png)

**Comment by yjc53** [comment]
一樣的問題，快速取詞功能時好時壞，但我非常享受閣下的字典，應該是 Chrome ext 上最好的查詞字典

**Comment by revir** [comment]
终于有时间改掉了这个严重的bug，大家应该收到更新了吧？ 再试试？
