### ISSUE TITLE
mac OSX 10.12 Chrome 版本 58.0.3029.96 (64-bit)

### ISSUE THREAD

**Issue by pyclear** [revir/FairyDict#3]
必须重启Chrome才能使用，建议安装后做个提示。
刚看到一个issue下回答说刷新可用，如果是这样的话也建议做个提示。

**Comment by revir** [comment]
谢谢反馈。一般的扩展安装后都需要刷新页面才能用的， 少数还可能需要重启。
不过不了解 Chrome 的用户确实不知道，应该加个提示。
