### ISSUE TITLE
屏幕取词

### ISSUE THREAD

**Issue by pyclear** [revir/FairyDict#4]
在屏幕取词后，点击x关闭弹窗，之后鼠标点击任何链接，都会跳出刚才搜索过的单词的弹窗。一两次后恢复正常。Chrome版本 58.0.3029.96 (64-bit)
ps: 屏幕取词的必须按住选项钩上后也是同样如此。

**Comment by revir** [comment]
2.5 版本来了，这个问题应该已经fix了。
