### ISSUE TITLE
弹窗替换成iframe可以吗？

### ISSUE THREAD

**Issue by juking** [revir/FairyDict#5]
弹窗的干扰太大了，为了防止打破样式，这样的选择有点过，可以考虑换成layer样式的iframe弹窗

**Comment by revir** [comment]
iframe 有诸多不便，跨域也不好操作，会让所有的快捷键失效的。
现在的弹窗体验更像一个独立的 APP， 永远只有一个窗口，鼠标、右键菜单、快捷键都可以呼出词典，甚至在观看pdf的时候也可以查词，iframe 恐怕难以做不到。

所以综上，暂时不想花力气研究 iframe.

**Comment by ricardo0624** [comment]
我也是这样想的,但是iframe有诸多不变的话,其实新窗口也是很中肯的,可以自定义大小,位置和缩放,另外我配合一些其它的插件,可以把不必要的内容过滤掉,更加整洁一些

**Comment by ricardo0624** [comment]
另外作者做的很好,鼓励一下,这款插件给我的帮助很大,谢谢了,已经star了

**Comment by revir** [comment]
@ricardo0624 

COOL, thanks.

你是指用去广告的插件过滤不必要的内容吗？ 还是有其他的好东西推荐？ LOL

**Comment by ricardo0624** [comment]
@revir 
是的，广告过滤插件有自定义功能，可以随意去除网站的内容，我用的是adsafe，把多余的东西去掉了
