### ISSUE TITLE
建议“开启鼠标快速查词功能”可以设置按住某个快捷键

### ISSUE THREAD

**Issue by jetma** [revir/FairyDict#6]
建议“开启鼠标快速查词功能”可以设置按住某个快捷键，现在这样有时候会影响到正常的选中。

**Comment by revir** [comment]
已有这个功能啊，进选项设置里设置。

**Comment by revir** [comment]
@jetma 
这个功能在 3.0.1 版本里加上了，之前我理解错了你的意思  :D
