### ISSUE TITLE
明明开启了同时按住alt，但选中单词还是会弹出小黑框，一直转

### ISSUE THREAD

**Issue by xczizz** [revir/FairyDict#7]
√ 开启鼠标取词功能
    √  同时必须按住Alt

但是，当我选中选中某个单词或某一句话的时候，会自动显示一个小框(不是弹出窗口)，但是小框没有翻译，是黑的，一直转。

之前没有，可能是你昨天更新完才出现的bug

**Comment by funnybones2015** [comment]
同问，也是出现了这个bug

**Comment by ricardo0624** [comment]
我的也是如此,关闭√ 开启鼠标取词功能 后,双击单词,会出现一个加载的黑框框

**Comment by revir** [comment]
这个黑框是前几天新增的**快速查词**功能，可以在设置里关掉。
与**鼠标取词**功能不相干。
此处的 Bug 是，有时候无法查询到释义，会一直转圈，此时在页面其他地方单击一下鼠标即可关闭这个黑框。
感谢大家的反馈，我会尽快修复这个问题。
